spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
#  jpa:
#    hibernate:
#      ddl-auto: none #update jezeli z entity non jezeli ze schema
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2

